name: Hello in NGINX Container

on: [push]

jobs:
  run-in-nginx:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Hello World inside NGINX container
        run: |
          docker run --rm nginx:latest bash -c "echo Hello World from inside NGINX container"
